# JavaScript Await 任务失败的问题
假如一个await任务失败了，会不会导致当前流程断掉？

参考：https://juejin.im/post/5ade84c951882567113ad246
```javascript
let fn1 = ()=>{
    return new Promise((resolve,reject) => {
        setTimeout(()=>{
            reject('故意抛出错误');
        },500);
    });
}

let fn2 = ()=>{
    return new Promise((resolve,reject)=>{
        setTimeout(()=>{
            resolve(1);
        },500);
    });
}

let getList = async ()=>{
    let a = await fn1();
    let b = await fn2();
    return {first: a,second:b};
}
getList().then(result=> {
    console.log(result);
}).catch(err=> {
    console.log(err);// 由于fn1的报错，async的状态直接变成了rejected
});
```

# tar.xz 文件处理
参考：https://blog.csdn.net/yjk13703623757/article/details/79848878

解压
```shell
tar -xvJf node-v8.11.1-linux-x64.tar.xz
```

压缩
```
tar -cvf xxx.tar xxx
xz -z xxx.tar
```
如果要保留被压缩的文件，需要加上参数-k

# ssh 远程启动服务的正确方式
参考：https://blog.csdn.net/oneinmore/article/details/50073443
```shell
cat nm.list | head -1 | xargs -Ixx -P 10 ssh xx '{ cd /path/to/prog && ./xxx arg1; } &>/dev/null &'
```

# 实现JS沙箱
参考： https://juejin.im/post/5d8d76b8e51d45781332e928